package io.github.the_infinite.framework.data;

import org.hibernate.SessionFactory;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.tool.schema.TargetType;
import org.hibernate.tool.schema.spi.*;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import java.util.zip.CRC32;

import io.github.the_infinite.framework.data.types.RepositoryOptions;
import io.github.the_infinite.framework.env.AppEnvironment;
import io.github.the_infinite.framework.logging.console.ConsoleLogger;
import io.github.the_infinite.framework.logging.correlation.CorrelationContext;
import io.github.the_infinite.framework.utils.DataHelpers;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;

@SuppressWarnings({"unused", "CallToPrintStackTrace", "BlockingMethodInNonBlockingContext"})
public class MigrationHelper {
  private static final String STATEMENT_BREAKPOINT = "--end of statement";

  private static String toJDBCUrl(String url) {
    final var usedUrl = url.trim();
    if (usedUrl.startsWith("jdbc:")) {
      return url;
    }
    return "jdbc:%s".formatted(usedUrl);
  }

  private static URI getMigrationOutputPath(String content) {
    final var name = DataHelpers.createToken(16, 20, 32, "", false);
    final var timestamp = System.currentTimeMillis();
    final var userDir = System.getProperty("user.dir");
    final var resourcesDir = new File(userDir, "src/main/resources/db/migrations");
    final var crc = new CRC32();
    crc.update(content.getBytes());

    return new File(resourcesDir, "%d-%d-%s.sql".formatted(timestamp, crc.getValue(), name)).toURI();
  }

  private static Optional<File> getRuntimeOutputPath() {
    final var classLoader = MigrationHelper.class.getClassLoader();
    try {
      final var resource = classLoader.getResource("db/migrations");
      if (resource == null) {
        return Optional.empty();
      }

      final var uri = resource.toURI();

      // Check if the application is running out of a packaged JAR file
      // In production/Docker, files are locked in the JAR. They cannot be represented as an OS File object.
      // We log a warning and return empty, skipping local File directory scans.
      if ("jar".equals(uri.getScheme())) {
        return Optional.empty();
      }

      // Works perfectly for local IDE testing
      return Optional.of(new File(uri));
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }


  private static Future<Void> createMigrationsTable(Vertx vertx, SessionFactory sessionFactory) {
    final var console = ConsoleLogger.getInstance(vertx);
    final var initialMigrationScriptActions = List.of(
      // Create the policy to ban updates.
      """
        CREATE OR REPLACE FUNCTION __internal_mgt_tm30_ban_updates() RETURNS TRIGGER AS
            $$
            BEGIN
              RAISE EXCEPTION 'Updates to finalized records are not allowed.';
            END;
            $$ LANGUAGE plpgsql;
        """,

      // Create the migration tables.
      """
          create table __database_migrations
          (
            id             BIGINT generated by default as identity,
            createdAt      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP not null,
            uid            UUID                                  not null,
            updatedAt      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP not null,
            checksum       bigint                                not null,
            data           TEXT,
            migration_name varchar(255)                          not null,
            primary key (id)
          );
        """,

      // Create the trigger to prevent updates.
      """
          CREATE TRIGGER prevent_migration_update
              BEFORE
                UPDATE
              ON __database_migrations
              FOR EACH ROW
            EXECUTE FUNCTION __internal_mgt_tm30_ban_updates();
        """,

      // Adding constraints.
      """
        alter table if exists __database_migrations
        drop constraint if exists UKsrnio194w0ic1jdt8h6ihg781;
        """,
      """
        alter table if exists __database_migrations
        add constraint UKsrnio194w0ic1jdt8h6ihg781 unique (uid);
        """,
      """
        alter table if exists __database_migrations
        drop constraint if exists UKllr0ja6npx3lubk3kqyk3t3oe;
        """,
      """
        alter table if exists __database_migrations
        add constraint UKllr0ja6npx3lubk3kqyk3t3oe unique (migration_name);
        """
    );

    try {
      return RepositoryActor.wrap(() -> {
        sessionFactory.fromTransaction(session -> {
          for (final var command : initialMigrationScriptActions) {
            session.createNativeQuery(command).executeUpdate();
          }
          session.flush();
          return null;
        });
        return null;
      });
    } catch (Exception e) {
      console.error("Failed to generate initial migration for creating the migrations table: " + e.getMessage());
      return Future.failedFuture(e);
    }
  }

  /**
   * Generates a migration script by comparing the local entity model with the remote database state.
   * Only generates a file if there are actual changes.
   * <p>
   * This method ensures that ALL existing migrations are applied first to establish the correct
   * database state as a baseline for comparison, which helps detect enum alterations and
   * subtractive changes more reliably.
   *
   * @return true if changes were detected and a migration script was generated, false otherwise.
   */
  public static boolean generate(Vertx vertx, SessionFactory sessionFactory) {
    final var env = AppEnvironment.getInstance();
    final var console = ConsoleLogger.getInstance(vertx);
    final var annotatedClasses = DataHelpers.findSubclasses(BaseEntity.class);
    annotatedClasses.removeIf(cls -> cls == BaseAuditableEntity.class || cls == BaseEntity.class);
    final var registryBuilder = new StandardServiceRegistryBuilder();
    final var migrationsRepo = new PersistentRepository<>(MigrationEntry.Modules.SYSTEM, MigrationEntry.class, sessionFactory);
    final var repositories = PersistentRepository.instances.keySet();

    //? If we have database classes that are not already registered in the repository instances, we should log a warning about them.
    for (final var entityClass : annotatedClasses) {
      if (repositories.contains(entityClass)) {
        continue;
      }

      console.warn("Database entity class '%s' has no registered repository instance.".formatted(entityClass.getName()));
    }

    if (env.getKind() != AppEnvironment.EnvironmentKind.DEVELOPMENT) {
      console.info("Would not attempt to generate migrations outside of development environment.");
      return false;
    }

    //? Check if this is the root directory of the project.
    if (!new File(System.getProperty("user.dir"), "src/main").exists()) {
      console.warn("Current directory does not appear to be the root of the project, skipping migration generation.");
      return false;
    }

    //? If the migration table does not exist, then we generate a migration just for the
    //? creation of the migration table, since we know that will be needed for any future
    //? migrations to be applied.
    if (!migrationsRepo.doesTableExist().await()) {
      console.info("Migrations table does not exist, generating initial migration for creating the migrations table...");
      createMigrationsTable(vertx, sessionFactory).await();
    }

    //? CRITICAL: Apply all existing migrations first to establish the correct database state as a baseline.
    //? This ensures that the schema comparison detects all changes, including enum
    //? alterations and subtractive changes.
    console.info("Applying all existing migrations before generating new ones to establish correct baseline...");
    try {
      migrate(vertx, sessionFactory).await();
    } catch (Exception e) {
      console.error("Failed to apply existing migrations before generation: " + e.getMessage());
      throw new RuntimeException("Cannot generate migrations without first applying existing migrations", e);
    }

    final Map<String, Object> dbConfig = Map.of(
      "jakarta.persistence.jdbc.url", toJDBCUrl(env.getPgUrl()),
      "hibernate.dialect", org.hibernate.dialect.PostgreSQLDialect.class.getName()
    );
    registryBuilder.applySettings(dbConfig);

    try (final var serviceRegistry = registryBuilder.build()) {
      final var metadataSources = new MetadataSources(serviceRegistry);
      annotatedClasses.forEach(metadataSources::addAnnotatedClass);
      final Metadata metadata = metadataSources.buildMetadata();
      final var bindings = metadata.getEntityBindings();

      final SchemaManagementTool tool = serviceRegistry.getService(SchemaManagementTool.class);
      if (tool == null) {
        throw new IllegalStateException("SchemaManagementTool service could not be retrieved");
      }
      final SchemaMigrator migrator = tool.getSchemaMigrator(dbConfig);

      final var options = new ExecutionOptions() {
        @Override
        public Map<String, Object> getConfigurationValues() {
          return dbConfig;
        }

        @Override
        public boolean shouldManageNamespaces() {
          return false;
        }

        @Override
        public ExceptionHandler getExceptionHandler() {
          return exception -> {
            throw new RuntimeException("Error executing migration command: " + exception.getMessage(), exception);
          };
        }
      };

      final StringBuilder commands = new StringBuilder();

      //? Now, we can start getting the diff using SchemaMigrator for standard DDL changes.
      final var targetDescriptor = new TargetDescriptor() {
        @Override
        public EnumSet<TargetType> getTargetTypes() {
          return EnumSet.of(TargetType.SCRIPT);
        }

        @Override
        public ScriptTargetOutput getScriptTargetOutput() {
          return new ScriptTargetOutput() {
            @Override
            public void prepare() {
            }

            @Override
            public void accept(String command) {
              command = command.trim();
              commands.append(command);

              if (!command.endsWith(";")) {
                commands.append(";");
              }

              commands.append("%s%s".formatted(STATEMENT_BREAKPOINT, System.lineSeparator()));
            }

            @Override
            public void release() {
            }
          };
        }
      };

      migrator.doMigration(metadata, options, ContributableMatcher.ALL, targetDescriptor);

      //? Note: By applying all migrations first (at the start of generate()), we ensure the database
      //? state is correct. This helps SchemaMigrator detect enum type changes and subtractive changes
      //? more reliably, since it compares against the actual current schema state.

      if (commands.isEmpty()) {
        return false;
      }

      final var outputPath = getMigrationOutputPath(commands.toString());
      final var file = new File(outputPath);

      //? If the parent directory does not exist, then we have a problem.
      if (!file.getParentFile().exists()) {
        try {
          if (file.getParentFile().mkdirs()) {
            console.exec("Created directories for migration output: " + file.getParentFile().getAbsolutePath());
          } else {
            throw new IOException("Failed to create directories for migration output: " + file.getParentFile().getAbsolutePath());
          }
        } catch (IOException e) {
          throw new RuntimeException("Could not write migration file: " + outputPath, e);
        }
      }

      //? If we find another migration that applies these same modifications...
      if (Arrays.stream(Objects.requireNonNull(file.getParentFile().list())).anyMatch(migrationFile -> {
        final var parts = migrationFile.split("-", 3);
        final var fileParts = file.getName().split("-", 3);
        final var checksum = parts[1];
        final var currentChecksum = fileParts[1];

        if (parts.length < 3) {
          return false;
        }

        return Objects.equals(parts[1], fileParts[1]);
      })) {
        console.info("A migration file with the same changes already exists, skipping generation.");
        return false;
      }

      //? Doing the most.
      console.info("Found %d entities to generate migrations for.".formatted(bindings.size()));

       //? Now you can say you are doing this because you really are.
       console.info("Generating migration script at " + outputPath.getPath());

       try (final var writer = new FileWriter(file)) {
         //? Append the earlier comments that instruct the user on the specifics of this
         //? file format. Include a note about validation pass for enum/subtractive changes.
         writer.write("""
           -- This file was generated by comparing the current entity model with the state of the database.
           -- It includes changes detected through standard Hibernate schema comparison.
           --
           -- Each command must be separated by the following comment, which is used as a breakpoint
           -- to split the commands when applying the migration: end of statement
           -- If you would like to modify the generated migration, you can edit this file, but be sure
           -- to keep the statement breakpoint comment between each command, otherwise the
           -- migration will fail to apply.
           --
           -- Note: All previously generated migrations were applied before generating this file to ensure
           -- the database state was correctly established as a baseline for comparison. This helps detect
           -- enum alterations, constraint modifications, and subtractive changes more reliably.
           -- Regards, Tobi of Moovable%s%s
           """.formatted(System.lineSeparator(), commands.toString()));
       } catch (Exception e) {
         throw new RuntimeException("Could not write migration file: " + outputPath, e);
       }

      return true;
    }
  }

  /**
   * Executes the migrations that have been generated and not yet applied to the database.
   * This should be run on application startup to ensure the database is up to date.
   */
  private static Future<Void> executeMigrations(final ConsoleLogger console, final SessionFactory sessionFactory, final List<File> migrationFiles, final List<MigrationEntry> migrations) {
    //? Fetch this first...
    final var migrationNames = migrations.stream().map(MigrationEntry::getMigrationName).collect(Collectors.toSet());
    final var unappliedMigrations = migrationFiles.stream().filter(file -> !migrationNames.contains(file.getName())).toList();

    //? If we find this, then we can continue...
    if (unappliedMigrations.isEmpty()) {
      console.exec("Nothing to migrate, database is up to date.");
      return Future.succeededFuture();
    }

    //? Apply
    console.info("Applying %d pending migrations...".formatted(unappliedMigrations.size()));

    return RepositoryActor.wrap(() -> {
      sessionFactory.fromStatelessTransaction(session -> {
        for (final var file : unappliedMigrations) {
          final String sql;
          try {
            sql = Files.readString(file.toPath());
          } catch (Exception e) {
            throw new RuntimeException("Failed to read migration file: " + file.getName(), e);
          }

          console.info("Applying migration " + file.getName());

          final var statements = Arrays.stream(sql.split(STATEMENT_BREAKPOINT))
            .map(cmd -> "%s;".formatted(cmd).trim())
            .filter(cmd -> !cmd.equals(";"))
            .toList();

          for (final var command : statements) {
            session.createNativeQuery(command).executeUpdate();
          }

          final var entry = new MigrationEntry();
          final var crc = new CRC32();
          crc.update(sql.getBytes());

          session.insert(
            entry.setMigrationName(file.getName())
              .setChecksum(crc.getValue())
              .setData(DataHelpers.toBase64(sql))
              .setUid(UUID.randomUUID())
          );

          console.exec("Applied " + file.getName());
        }
        return null;
      });
      return null;
    });
  }

  /**
   * The main method to run the migration generation standalone.
   */
  public static Future<Void> migrate(Vertx vertx, SessionFactory sessionFactory) {
    try {
      final var promise = Promise.<Void>promise();
      final var console = ConsoleLogger.getInstance(vertx);
      final var migrationsRepo = new PersistentRepository<>(MigrationEntry.Modules.SYSTEM, MigrationEntry.class, sessionFactory);
      final var classLoader = MigrationHelper.class.getClassLoader();
      final var resource = classLoader.getResource("db/migrations");
      final List<File> migrationFiles = new ArrayList<>();

      // No migration resources packaged yet is a valid state (e.g., first deployment).
      if (resource == null) {
        console.warn("No 'db/migrations' folder found in resources; continuing with zero migration files.");
      } else {
        final var uri = resource.toURI();

        // Scenario A: Running inside a packaged JAR (Docker / Production)
        if ("jar".equals(uri.getScheme())) {
          // Create an isolated virtual filesystem scope to crawl the ZIP contents
          try (FileSystem fileSystem = FileSystems.newFileSystem(uri, Collections.emptyMap())) {
            final var migrationFolder = fileSystem.getPath("db/migrations");
            if (Files.exists(migrationFolder)) {
              try (Stream<Path> walkStream = Files.walk(migrationFolder, 1)) {
                final var tempDir = new File(System.getProperty("java.io.tmpdir"), "extracted-migrations");
                if (!tempDir.exists() && !tempDir.mkdirs()) {
                  throw new IOException("Failed to create temporary migration directory: " + tempDir.getAbsolutePath());
                }

                final var pathsList = walkStream
                  .filter(Files::isRegularFile)
                  .filter(path -> path.getFileName().toString().endsWith(".sql"))
                  .sorted(Comparator.comparing(path -> path.getFileName().toString()))
                  .toList();

                for (final var path : pathsList) {
                  final var fileName = path.getFileName().toString();
                  final var tempFile = new File(tempDir, fileName);

                  // Copy the file out of the JAR into /tmp so executeMigrations can read it as a normal File
                  try (final var is = classLoader.getResourceAsStream("db/migrations/" + fileName)) {
                    if (is != null) {
                      Files.copy(is, tempFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                      migrationFiles.add(tempFile);
                    }
                  }
                }
              }
            } else {
              console.warn("No migration files found in packaged resources; continuing with zero migration files.");
            }
          }
        }

        else {
          final var outputDir = new File(uri);
          if (!outputDir.exists()) {

            // If we could create this...
            if (outputDir.mkdirs()) {
              ConsoleLogger.getInstance(vertx).exec("Created migration output directory: " + outputDir.getAbsolutePath());
            }

            // Could not do this.
            else {
              promise.fail(new IOException("Failed to create migration output directory: " + outputDir.getAbsolutePath()));
              return promise.future();
            }
          }

          // Get the current sorted files from the local folder
          final var localFiles = outputDir.listFiles();
          if (localFiles != null) {
            migrationFiles.addAll(Arrays.stream(localFiles)
              .sorted(Comparator.comparing(File::getName))
              .toList());
          }
        }
      }

      // Okay then. Proceed with your exact database matching checks
      migrationsRepo.doesTableExist().onFailure(promise::fail).onSuccess(exists -> {
        // If this does not exist, then we can just run the migrations without checking for applied ones, since there are none.
        if (!exists) {
          console.info("Migrations table does not exist, applying all migrations...");
          createMigrationsTable(vertx, sessionFactory)
            .onFailure(promise::fail)
            .onSuccess(v -> executeMigrations(console, sessionFactory, migrationFiles, List.of())
              .onSuccess(ignored -> promise.succeed())
              .onFailure(promise::fail));
          return;
        }

        // Since it exists, we need to check which migrations have been applied and only run the ones that have not been applied.
        migrationsRepo.getMany(
            null,
            new RepositoryOptions<MigrationEntry>(CorrelationContext.from(vertx.getOrCreateContext())).setLimit(3000),
            null
          )
          .onFailure(promise::fail)
          .onSuccess(migrations -> executeMigrations(console, sessionFactory, migrationFiles, migrations)
            .onSuccess(ignored -> promise.succeed())
            .onFailure(promise::fail));
      });

      return promise.future();
    } catch (Exception e) {
      if (e.getCause() != null) {
        return Future.failedFuture(e.getCause());
      }
      return Future.failedFuture(e);
    }
  }

}
