package io.github.the_infinite.framework.data;

import org.hibernate.SessionFactory;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.dialect.Dialect;
import org.hibernate.mapping.Column;
import org.hibernate.tool.schema.TargetType;
import org.hibernate.tool.schema.spi.*;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.nio.file.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import java.util.zip.CRC32;

import io.github.the_infinite.framework.data.types.RepositoryOptions;
import io.github.the_infinite.framework.env.AppEnvironment;
import io.github.the_infinite.framework.logging.console.ConsoleLogger;
import io.github.the_infinite.framework.logging.correlation.CorrelationContext;
import io.github.the_infinite.framework.utils.DataHelpers;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import lombok.extern.slf4j.Slf4j;

@SuppressWarnings({"unused", "BlockingMethodInNonBlockingContext", "deprecation"})
@Slf4j
public class MigrationHelper {
  private static final String STATEMENT_BREAKPOINT = "--end of statement";

  /**
   * Tables that the subtractive diff must never drop, even if they are not part of the entity
   * model. This protects third-party / infrastructure tables that may live in the same schema as
   * the application's managed tables.
   */
  private static final Set<String> IGNORED_TABLES = Set.of(
    "__database_migrations",
    "__database_seeders",
    "flyway_schema_history",
    "databasechangelog",
    "databasechangeloglock",
    "spatial_ref_sys",
    "geometry_columns",
    "geography_columns"
  );

  private static String toJDBCUrl(String url) {
    final var usedUrl = url.trim();
    if (usedUrl.startsWith("jdbc:")) {
      return url;
    }
    return "jdbc:%s".formatted(usedUrl);
  }

  private static URI getMigrationOutputPath(String content) {
    final var name = DataHelpers.createToken(16, 20, 32, "", false);
    final var timestamp = System.currentTimeMillis();
    final var userDir = System.getProperty("user.dir");
    final var resourcesDir = new File(userDir, "src/main/resources/db/migrations");
    final var crc = new CRC32();
    crc.update(content.getBytes());

    return new File(resourcesDir, "%d-%d-%s.sql".formatted(timestamp, crc.getValue(), name)).toURI();
  }

  private static Optional<File> getRuntimeOutputPath() {
    final var classLoader = MigrationHelper.class.getClassLoader();
    try {
      final var resource = classLoader.getResource("db/migrations");
      if (resource == null) {
        return Optional.empty();
      }

      final var uri = resource.toURI();

      // Check if the application is running out of a packaged JAR file
      // In production/Docker, files are locked in the JAR. They cannot be represented as an OS File object.
      // We log a warning and return empty, skipping local File directory scans.
      if ("jar".equals(uri.getScheme())) {
        return Optional.empty();
      }

      // Works perfectly for local IDE testing
      return Optional.of(new File(uri));
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }


  private static Future<Void> createMigrationsTable(Vertx vertx, SessionFactory sessionFactory) {
    final var console = ConsoleLogger.getInstance(vertx);
    final var initialMigrationScriptActions = List.of(
      // Create the policy to ban updates.
      """
        CREATE OR REPLACE FUNCTION __internal_mgt_tm30_ban_updates() RETURNS TRIGGER AS
            $$
            BEGIN
              RAISE EXCEPTION 'Updates to finalized records are not allowed.';
            END;
            $$ LANGUAGE plpgsql;
        """,

      // Create the migration tables.
      """
          create table __database_migrations
          (
            id             BIGINT generated by default as identity,
            createdAt      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP not null,
            uid            UUID                                  not null,
            updatedAt      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP not null,
            checksum       bigint                                not null,
            data           TEXT,
            migration_name varchar(255)                          not null,
            primary key (id)
          );
        """,

      // Create the trigger to prevent updates.
      """
          CREATE TRIGGER prevent_migration_update
              BEFORE
                UPDATE
              ON __database_migrations
              FOR EACH ROW
            EXECUTE FUNCTION __internal_mgt_tm30_ban_updates();
        """,

      // Adding constraints.
      """
        alter table if exists __database_migrations
        drop constraint if exists UKsrnio194w0ic1jdt8h6ihg781;
        """,
      """
        alter table if exists __database_migrations
        add constraint UKsrnio194w0ic1jdt8h6ihg781 unique (uid);
        """,
      """
        alter table if exists __database_migrations
        drop constraint if exists UKllr0ja6npx3lubk3kqyk3t3oe;
        """,
      """
        alter table if exists __database_migrations
        add constraint UKllr0ja6npx3lubk3kqyk3t3oe unique (migration_name);
        """
    );

    try {
      return RepositoryActor.wrap(() -> {
        sessionFactory.fromTransaction(session -> {
          for (final var command : initialMigrationScriptActions) {
            session.createNativeQuery(command).executeUpdate();
          }
          session.flush();
          return null;
        });
        return null;
      });
    } catch (Exception e) {
      console.error("Failed to generate initial migration for creating the migrations table: " + e.getMessage());
      return Future.failedFuture(e);
    }
  }

  /**
   * Generates a migration script by comparing the local entity model with the remote database state.
   * Only generates a file if there are actual changes.
   * <p>
   * This method ensures that ALL existing migrations are applied first to establish the correct
   * database state as a baseline for comparison, which helps detect enum alterations and
   * subtractive changes more reliably.
   *
   * @return true if changes were detected and a migration script was generated, false otherwise.
   */
  public static boolean generate(Vertx vertx, SessionFactory sessionFactory) {
    final var env = AppEnvironment.getInstance();
    final var console = ConsoleLogger.getInstance(vertx);
    final var annotatedClasses = DataHelpers.findSubclasses(BaseEntity.class);
    annotatedClasses.removeIf(cls -> cls == BaseAuditableEntity.class || cls == BaseEntity.class);
    final var registryBuilder = new StandardServiceRegistryBuilder();
    final var migrationsRepo = new PersistentRepository<>(MigrationEntry.Modules.SYSTEM, MigrationEntry.class, sessionFactory);
    final var repositories = PersistentRepository.instances.keySet();

    //? If we have database classes that are not already registered in the repository instances, we should log a warning about them.
    for (final var entityClass : annotatedClasses) {
      if (repositories.contains(entityClass)) {
        continue;
      }

      console.warn("Database entity class '%s' has no registered repository instance.".formatted(entityClass.getName()));
    }

    if (env.getKind() != AppEnvironment.EnvironmentKind.DEVELOPMENT) {
      console.info("Would not attempt to generate migrations outside of development environment.");
      return false;
    }

    //? Check if this is the root directory of the project.
    if (!new File(System.getProperty("user.dir"), "src/main").exists()) {
      console.warn("Current directory does not appear to be the root of the project, skipping migration generation.");
      return false;
    }

    //? If the migration table does not exist, then we generate a migration just for the
    //? creation of the migration table, since we know that will be needed for any future
    //? migrations to be applied.
    if (!migrationsRepo.doesTableExist().await()) {
      console.info("Migrations table does not exist, generating initial migration for creating the migrations table...");
      createMigrationsTable(vertx, sessionFactory).await();
    }

    //? CRITICAL: Apply all existing migrations first to establish the correct database state as a baseline.
    //? This ensures that the schema comparison detects all changes, including enum
    //? alterations and subtractive changes.
    console.info("Applying all existing migrations before generating new ones to establish correct baseline...");
    try {
      migrate(vertx, sessionFactory).await();
    } catch (Exception e) {
      console.error("Failed to apply existing migrations before generation: " + e.getMessage());
      throw new RuntimeException("Cannot generate migrations without first applying existing migrations", e);
    }

    final Map<String, Object> dbConfig = Map.of(
      "jakarta.persistence.jdbc.url", toJDBCUrl(env.getPgUrl()),
      "hibernate.dialect", org.hibernate.dialect.PostgreSQLDialect.class.getName(),
      //? Use RECREATE_QUIETLY so the additive migrator only *adds* missing unique constraints and
      //? never drops/recreates existing ones. This is critical for anonymous unique constraints
      //? (e.g. @Column(unique = true) on BaseEntity.uid) which Hibernate names implicitly and which
      //? the default DROP_RECREATE_QUIETLY strategy would otherwise drop on every single generation.
      //? Removed unique constraints are handled separately by the subtractive diff pass below.
      org.hibernate.cfg.SchemaToolingSettings.UNIQUE_CONSTRAINT_SCHEMA_UPDATE_STRATEGY,
      org.hibernate.tool.schema.UniqueConstraintSchemaUpdateStrategy.RECREATE_QUIETLY
    );
    registryBuilder.applySettings(dbConfig);

    try (final var serviceRegistry = registryBuilder.build()) {
      final var metadataSources = new MetadataSources(serviceRegistry);
      annotatedClasses.forEach(metadataSources::addAnnotatedClass);
      final Metadata metadata = metadataSources.buildMetadata();
      final var bindings = metadata.getEntityBindings();

      final SchemaManagementTool tool = serviceRegistry.getService(SchemaManagementTool.class);
      if (tool == null) {
        throw new IllegalStateException("SchemaManagementTool service could not be retrieved");
      }
      final SchemaMigrator migrator = tool.getSchemaMigrator(dbConfig);

      final var options = new ExecutionOptions() {
        @Override
        public Map<String, Object> getConfigurationValues() {
          return dbConfig;
        }

        @Override
        public boolean shouldManageNamespaces() {
          return false;
        }

        @Override
        public ExceptionHandler getExceptionHandler() {
          return exception -> {
            throw new RuntimeException("Error executing migration command: " + exception.getMessage(), exception);
          };
        }
      };

      final StringBuilder commands = new StringBuilder();

      //? Now, we can start getting the diff using SchemaMigrator for standard DDL changes.
      final var targetDescriptor = new TargetDescriptor() {
        @Override
        public EnumSet<TargetType> getTargetTypes() {
          return EnumSet.of(TargetType.SCRIPT);
        }

        @Override
        public ScriptTargetOutput getScriptTargetOutput() {
          return new ScriptTargetOutput() {
            @Override
            public void prepare() {
            }

            @Override
            public void accept(String command) {
              command = command.trim();
              commands.append(command);

              if (!command.endsWith(";")) {
                commands.append(";");
              }

              commands.append("%s%s".formatted(STATEMENT_BREAKPOINT, System.lineSeparator()));
            }

            @Override
            public void release() {
            }
          };
        }
      };

      migrator.doMigration(metadata, options, ContributableMatcher.ALL, targetDescriptor);

      //? The additive SchemaMigrator above only ever *adds* tables, columns, indexes and
      //? constraints. It never detects objects that were removed from or changed in the entity
      //? model (dropped tables/columns, modified nullability, etc.). We therefore run a second,
      //? subtractive pass that compares the entity model against the live database and emits the
      //? corresponding DROP / ALTER statements. By applying all migrations first (above), the
      //? database already reflects every object that is still part of the model, so anything left
      //? over in the database but absent from the model is genuinely removed and safe to drop.
      final var dialect = metadata.getDatabase().getJdbcEnvironment().getDialect();
      final var subtractiveCommands = RepositoryActor.wrap(() ->
        sessionFactory.fromTransaction(session ->
          session.doReturningWork(connection -> computeSubtractiveChanges(metadata, dialect, connection))
        )
      ).await();

      for (final var command : subtractiveCommands) {
        commands.append(command);
        commands.append(";");
        commands.append("%s%s".formatted(STATEMENT_BREAKPOINT, System.lineSeparator()));
      }

      //? Note: By applying all migrations first (at the start of generate()), we ensure the database
      //? state is correct. This helps SchemaMigrator detect enum type changes more reliably, since it
      //? compares against the actual current schema state. The separate subtractive pass (above) then
      //? handles removed tables/columns and nullability changes that Hibernate's migrator ignores.
      if (commands.isEmpty()) {
        return false;
      }

      final var outputPath = getMigrationOutputPath(commands.toString());
      final var file = new File(outputPath);

      //? If the parent directory does not exist, then we have a problem.
      if (!file.getParentFile().exists()) {
        try {
          if (file.getParentFile().mkdirs()) {
            console.exec("Created directories for migration output: " + file.getParentFile().getAbsolutePath());
          } else {
            throw new IOException("Failed to create directories for migration output: " + file.getParentFile().getAbsolutePath());
          }
        } catch (IOException e) {
          throw new RuntimeException("Could not write migration file: " + outputPath, e);
        }
      }

      //? If we find another migration that applies these same modifications...
      if (Arrays.stream(Objects.requireNonNull(file.getParentFile().list())).anyMatch(migrationFile -> {
        final var parts = migrationFile.split("-", 3);
        final var fileParts = file.getName().split("-", 3);
        final var checksum = parts[1];
        final var currentChecksum = fileParts[1];

        if (parts.length < 3) {
          return false;
        }

        return Objects.equals(parts[1], fileParts[1]);
      })) {
        console.info("A migration file with the same changes already exists, skipping generation.");
        return false;
      }

      //? Doing the most.
      console.info("Found %d entities to generate migrations for.".formatted(bindings.size()));

      //? Now you can say you are doing this because you really are.
      console.info("Generating migration script at " + outputPath.getPath());

      try (final var writer = new FileWriter(file)) {
        //? Append the earlier comments that instruct the user on the specifics of this
        //? file format. Include a note about validation pass for enum/subtractive changes.
        writer.write("""
          -- This file was generated by comparing the current entity model with the state of the database.
          -- It includes changes detected through standard Hibernate schema comparison.
          --
          -- Each command must be separated by the following comment, which is used as a breakpoint
          -- to split the commands when applying the migration: end of statement
          -- If you would like to modify the generated migration, you can edit this file, but be sure
          -- to keep the statement breakpoint comment between each command, otherwise the
          -- migration will fail to apply.
          --
          -- Note: All previously generated migrations were applied before generating this file to ensure
          -- the database state was correctly established as a baseline for comparison. This helps detect
          -- enum alterations, constraint modifications, and subtractive changes more reliably.
          -- Regards, Tobi of Moovable%s%s
          """.formatted(System.lineSeparator(), commands.toString()));
      } catch (Exception e) {
        throw new RuntimeException("Could not write migration file: " + outputPath, e);
      }

      return true;
    }
  }

  /**
   * Computes the "subtractive" side of the schema diff that Hibernate's {@link SchemaMigrator}
   * never produces: objects that exist in the database but are no longer present in (or differ
   * from) the entity model.
   * <p>
   * This detects:
   * <ul>
   *   <li>tables that were removed from the model ({@code DROP TABLE ... CASCADE})</li>
   *   <li>columns that were removed from the model ({@code ALTER TABLE ... DROP COLUMN ... CASCADE})</li>
   *   <li>columns whose nullability changed in the model ({@code ALTER TABLE ... ALTER COLUMN ... SET/DROP NOT NULL})</li>
   *   <li>columns whose default value changed in the model ({@code ALTER TABLE ... ALTER COLUMN ... SET/DROP DEFAULT})</li>
   *   <li>unique constraints / unique indexes that were removed from the model ({@code ALTER TABLE ... DROP CONSTRAINT} / {@code DROP INDEX})</li>
   * </ul>
   * Additive changes (new tables/columns/indexes/constraints and column type/length changes) are
   * already emitted by the standard {@link SchemaMigrator} and are intentionally left to it to avoid
   * generating duplicate statements.
   *
   * @param metadata  the fully built Hibernate entity model metadata
   * @param dialect   the active database dialect, used for identifier quoting
   * @param connection a live JDBC connection to introspect the current database schema
   * @return the ordered list of subtractive DDL statements to append to the migration
   */
  @SuppressWarnings("SqlSourceToSinkFlow")
  private static List<String> computeSubtractiveChanges(
    final Metadata metadata,
    final Dialect dialect,
    final Connection connection
  ) throws SQLException {
    final var statements = new ArrayList<String>();

    //? Build the model view: for every physical table we track the columns it manages, their
    //? nullability / default, and the set of column-sets the model requires to be unique. A unique
    //? requirement can be expressed three ways: an explicit @UniqueConstraint (UniqueKey), a unique
    //? @Index, or a single column marked @Column(unique = true). The last is "anonymous" and Hibernate
    //? frequently does NOT surface it as a UniqueKey, so we also derive it from the column's isUnique()
    //? flag. Matching dropped constraints by their *column set* (rather than by the auto-generated
    //? constraint name) is what keeps still-modeled constraints - such as the uid unique constraint on a
    //? BaseEntity - from being dropped.
    final Map<String, Set<String>> managedColumns = new HashMap<>();
    final Map<String, Map<String, Boolean>> managedNotNull = new HashMap<>();
    final Map<String, Map<String, String>> managedDefaults = new HashMap<>();
    final Map<String, Set<Set<String>>> managedUniqueColumnSets = new HashMap<>();
    for (final var table : metadata.collectTableMappings()) {
      if (!table.isPhysicalTable()) {
        continue;
      }

      final var tableName = table.getName().toLowerCase(Locale.ROOT);
      final var columns = managedColumns.computeIfAbsent(tableName, k -> new HashSet<>());
      final var notNull = managedNotNull.computeIfAbsent(tableName, k -> new HashMap<>());
      final var defaults = managedDefaults.computeIfAbsent(tableName, k -> new HashMap<>());
      final var uniqueSets = managedUniqueColumnSets.computeIfAbsent(tableName, k -> new HashSet<>());

      for (final var column : table.getColumns()) {
        final var columnName = column.getName().toLowerCase(Locale.ROOT);
        columns.add(columnName);
        notNull.put(columnName, !column.isNullable());
        defaults.put(columnName, extractModelDefault(column));

        //? Anonymous single-column uniqueness (e.g. @Column(unique = true) on BaseEntity.uid).
        if (column.isUnique()) {
          uniqueSets.add(Set.of(columnName));
        }
      }

      for (final var uniqueKey : table.getUniqueKeys().values()) {
        uniqueSets.add(toColumnNameSet(uniqueKey.getColumns()));
      }
      for (final var index : table.getIndexes().values()) {
        if (index.isUnique()) {
          uniqueSets.add(toColumnNameSet(index.getColumns()));
        }
      }
    }

    //? Resolve the schema we are inspecting. The entity model is deployed against the connection's
    //? current schema, so we only ever compare against objects living in that schema.
    var schema = connection.getSchema();
    if (schema == null || schema.isBlank()) {
      schema = "public";
    }
    final var quotedSchema = schema.replace("'", "''");

    final var dbTables = new HashSet<String>();
    final Map<String, Set<String>> dbColumns = new HashMap<>();
    //? Keep the original-case identifiers for emission; comparison is always done on the lowercased keys.
    final Map<String, String> dbTableNames = new HashMap<>();
    final Map<String, Map<String, String>> dbColumnNames = new HashMap<>();
    final Map<String, Map<String, Boolean>> dbNullable = new HashMap<>();
    final Map<String, Map<String, String>> dbDefaults = new HashMap<>();
    //? table -> (constraint/index name -> set of column names it covers) for unique objects in the database
    final Map<String, Map<String, Set<String>>> dbUniqueConstraints = new HashMap<>();
    final Map<String, Map<String, Set<String>>> dbUniqueIndexes = new HashMap<>();

    try (final Statement statement = connection.createStatement();
         final ResultSet columns = statement.executeQuery(
           "select table_name, column_name, is_nullable, column_default from information_schema.columns " +
             "where table_schema = '" + quotedSchema + "'")) {
      while (columns.next()) {
        final var tableNameKey = columns.getString(1).toLowerCase(Locale.ROOT);
        final var columnNameKey = columns.getString(2).toLowerCase(Locale.ROOT);
        final var tableName = columns.getString(1);
        final var columnName = columns.getString(2);
        final var nullable = "YES".equalsIgnoreCase(columns.getString(3));
        final var defaultExpr = columns.getString(4);
        dbTables.add(tableNameKey);
        dbTableNames.put(tableNameKey, tableName);
        dbColumns.computeIfAbsent(tableNameKey, k -> new HashSet<>()).add(columnNameKey);
        dbColumnNames.computeIfAbsent(tableNameKey, k -> new HashMap<>()).put(columnNameKey, columnName);
        dbNullable.computeIfAbsent(tableNameKey, k -> new HashMap<>()).put(columnNameKey, nullable);
        dbDefaults.computeIfAbsent(tableNameKey, k -> new HashMap<>()).put(columnNameKey, defaultExpr);
      }
    }

    try (final Statement statement = connection.createStatement();
         final ResultSet constraints = statement.executeQuery(
           "select tc.table_name, tc.constraint_name, kcu.column_name " +
             "from information_schema.table_constraints tc " +
             "join information_schema.key_column_usage kcu " +
             "  on tc.constraint_name = kcu.constraint_name " +
             " and tc.table_schema = kcu.table_schema " +
             " and tc.table_name = kcu.table_name " +
             "where tc.constraint_type = 'UNIQUE' and tc.table_schema = '" + quotedSchema + "' " +
             "order by tc.table_name, tc.constraint_name, kcu.ordinal_position")) {
      while (constraints.next()) {
        final var tableName = constraints.getString(1).toLowerCase(Locale.ROOT);
        final var constraintName = constraints.getString(2);
        final var columnName = constraints.getString(3).toLowerCase(Locale.ROOT);
        dbUniqueConstraints
          .computeIfAbsent(tableName, k -> new HashMap<>())
          .computeIfAbsent(constraintName, k -> new HashSet<>())
          .add(columnName);
      }
    }

    try (final Statement statement = connection.createStatement();
         final ResultSet indexes = statement.executeQuery(
           "select i.relname, ci.relname, a.attname " +
             "from pg_index idx " +
             "join pg_class i on i.oid = idx.indrelid " +
             "join pg_class ci on ci.oid = idx.indexrelid " +
             "join pg_namespace n on n.oid = i.relnamespace " +
             "join pg_attribute a on a.attrelid = i.oid and a.attnum = any(idx.indkey) " +
             "where idx.indisunique and not idx.indisprimary and n.nspname = '" + quotedSchema + "' " +
             "and not exists (" +
             "  select 1 from information_schema.table_constraints tc " +
             "  where tc.constraint_type = 'UNIQUE' and tc.table_schema = n.nspname " +
             "    and tc.table_name = i.relname and tc.constraint_name = ci.relname) " +
             "order by i.relname, ci.relname, a.attnum")) {
      while (indexes.next()) {
        final var tableName = indexes.getString(1).toLowerCase(Locale.ROOT);
        final var indexName = indexes.getString(2);
        final var columnName = indexes.getString(3).toLowerCase(Locale.ROOT);
        dbUniqueIndexes
          .computeIfAbsent(tableName, k -> new HashMap<>())
          .computeIfAbsent(indexName, k -> new HashSet<>())
          .add(columnName);
      }
    }

    //? Drop unique constraints / indexes whose column set is no longer required to be unique by the model.
    //? Matching by column set (not by the auto-generated constraint name) is what prevents still-modeled
    //? constraints - such as the anonymous unique constraint on BaseEntity.uid - from being dropped. Foreign
    //? keys are never touched, because this only inspects UNIQUE constraints and unique indexes.
    for (final var entry : managedColumns.entrySet()) {
      final var tableName = entry.getKey();
      final var emitTable = dbTableNames.getOrDefault(tableName, tableName);
      final var modelUniqueSets = managedUniqueColumnSets.getOrDefault(tableName, Set.of());

      for (final var constraint : dbUniqueConstraints.getOrDefault(tableName, Map.of()).entrySet()) {
        if (!constraint.getValue().isEmpty() && notCoveredByAny(constraint.getValue(), modelUniqueSets)) {
          statements.add("alter table %s drop constraint if exists %s".formatted(dialect.quote(emitTable), dialect.quote(constraint.getKey())));
        }
      }

      for (final var index : dbUniqueIndexes.getOrDefault(tableName, Map.of()).entrySet()) {
        if (!index.getValue().isEmpty() && notCoveredByAny(index.getValue(), modelUniqueSets)) {
          statements.add("drop index if exists %s".formatted(dialect.quote(index.getKey())));
        }
      }
    }

    //? For tables that are still modeled, drop columns that were removed and reconcile nullability
    //? and default values.
    for (final var entry : managedColumns.entrySet()) {
      final var tableName = entry.getKey();
      final var emitTable = dbTableNames.getOrDefault(tableName, tableName);
      final var columnNames = dbColumnNames.getOrDefault(tableName, Map.of());
      if (!dbTables.contains(tableName)) {
        //? The table itself is missing (it will be created by the additive migrator) or is being
        //? dropped entirely below, so column-level changes are irrelevant.
        continue;
      }

      final var modelColumns = entry.getValue();
      final var modelNotNull = managedNotNull.get(tableName);
      final var modelDefaults = managedDefaults.get(tableName);
      final var existingColumns = dbColumns.getOrDefault(tableName, Set.of());
      final var existingNullable = dbNullable.getOrDefault(tableName, Map.of());
      final var existingDefaults = dbDefaults.getOrDefault(tableName, Map.of());

      for (final var dbColumn : existingColumns) {
        final var emitColumn = columnNames.getOrDefault(dbColumn, dbColumn);
        if (!modelColumns.contains(dbColumn)) {
          statements.add("alter table if exists %s drop column %s cascade".formatted(dialect.quote(emitTable), dialect.quote(emitColumn)));
          continue;
        }

        //? The column exists in both, so check whether its nullability was changed in the model.
        final var modelRequired = modelNotNull.get(dbColumn);
        final var dbColumnNullable = existingNullable.get(dbColumn);
        if (modelRequired != null && dbColumnNullable != null) {
          final var dbColumnNotNull = !dbColumnNullable;
          if (modelRequired != dbColumnNotNull) {
            final var action = modelRequired ? "set not null" : "drop not null";
            statements.add("alter table if exists %s alter column %s %s".formatted(dialect.quote(emitTable), dialect.quote(emitColumn), action));
          }
        }

        //? The default value may have been added, changed or removed in the model.
        final var modelDefault = modelDefaults.get(dbColumn);
        final var dbDefault = existingDefaults.get(dbColumn);
        final var modelNormalized = normalizeDefault(modelDefault);
        final var dbNormalized = normalizeDefault(dbDefault);
        if (modelNormalized == null) {
          if (dbNormalized != null) {
            statements.add("alter table if exists %s alter column %s drop default".formatted(dialect.quote(emitTable), dialect.quote(emitColumn)));
          }
        } else if (!modelNormalized.equals(dbNormalized)) {
          statements.add("alter table if exists %s alter column %s set default %s".formatted(dialect.quote(emitTable), dialect.quote(emitColumn), modelDefault));
        }
      }
    }

    //? Tables that exist in the database but are no longer part of the entity model are removed.
    //? Done last so that dependent objects are dropped alongside the table.
    for (final var dbTable : dbTables) {
      if (managedColumns.containsKey(dbTable) || IGNORED_TABLES.contains(dbTable)) {
        continue;
      }

      statements.add("drop table if exists %s cascade".formatted(dialect.quote(dbTableNames.getOrDefault(dbTable, dbTable))));
    }

    return statements;
  }

  /**
   * Extracts the model-side default value expression for a column, if any. This is populated when the
   * entity uses Hibernate's {@code @ColumnDefault} (or equivalent). Note that defaults expressed
   * purely inside a {@code columnDefinition} fragment are not retrievable from the built metadata and
   * are therefore not diffed here; the additive migrator has the same limitation.
   */
  private static String extractModelDefault(final Column column) {
    final var explicit = column.getDefaultValue();
    if (explicit != null && !explicit.isBlank()) {
      return explicit.trim();
    }

    return null;
  }

  /**
   * Normalizes a default-value expression for comparison. PostgreSQL stores literal defaults with a
   * trailing type cast (e.g. {@code 'x'::text}, {@code 'x'::character varying},
   * {@code 'x'::timestamp without time zone}, {@code 'x'::text[]}) and sometimes wraps expression
   * defaults in parentheses. We strip both so the comparison focuses on the actual value rather than
   * on representation differences between the model and the live catalog.
   */
  private static String normalizeDefault(final String expression) {
    if (expression == null) {
      return null;
    }

    var normalized = expression.trim();
    if (normalized.endsWith(";")) {
      normalized = normalized.substring(0, normalized.length() - 1).trim();
    }
    //? A cast is always the terminal token. The character class deliberately excludes quotes so we
    //? never consume into a string literal (e.g. a value that happens to contain "::").
    normalized = normalized.replaceAll("(?i)\\s*::[\\w\\s*\\[\\],()]+$", "");
    //? Strip a single layer of balanced surrounding parentheses (PostgreSQL wraps expression defaults,
    //? e.g. (now() + '1 day'::interval)).
    if (normalized.startsWith("(") && normalized.endsWith(")") && balancedParentheses(normalized.substring(1, normalized.length() - 1))) {
      normalized = normalized.substring(1, normalized.length() - 1).trim();
    }
    //? Compare case-insensitively for SQL keywords/functions while preserving the exact content of
    //? string literals.
    normalized = lowerCaseOutsideQuotes(normalized);
    return normalized.isBlank() ? null : normalized;
  }

  private static boolean balancedParentheses(final String value) {
    int depth = 0;
    boolean inString = false;
    for (int i = 0; i < value.length(); i++) {
      final var c = value.charAt(i);
      if (c == '\'') {
        inString = !inString;
      } else if (!inString) {
        if (c == '(') {
          depth++;
        } else if (c == ')') {
          depth--;
          if (depth < 0) {
            return false;
          }
        }
      }
    }
    return depth == 0 && !inString;
  }

  private static String lowerCaseOutsideQuotes(final String value) {
    final var builder = new StringBuilder(value.length());
    boolean inString = false;
    for (int i = 0; i < value.length(); i++) {
      final var c = value.charAt(i);
      if (c == '\'') {
        inString = !inString;
        builder.append(c);
      } else if (inString) {
        builder.append(c);
      } else {
        builder.append(Character.toLowerCase(c));
      }
    }
    return builder.toString();
  }

  private static Set<String> toColumnNameSet(final List<Column> columns) {
    final var names = new HashSet<String>();
    for (final var column : columns) {
      names.add(column.getName().toLowerCase(Locale.ROOT));
    }
    return names;
  }

  private static boolean notCoveredByAny(final Set<String> dbColumnSet, final Set<Set<String>> modelUniqueSets) {
    if (dbColumnSet.isEmpty()) {
      return true;
    }
    for (final var modelSet : modelUniqueSets) {
      if (modelSet.equals(dbColumnSet)) {
        return false;
      }
    }
    return true;
  }

  /**
   * Executes the migrations that have been generated and not yet applied to the database.
   * This should be run on application startup to ensure the database is up to date.
   */
  private static Future<Void> executeMigrations(final ConsoleLogger console, final SessionFactory sessionFactory, final List<File> migrationFiles, final List<MigrationEntry> migrations) {
    //? Fetch this first...
    final var migrationNames = migrations.stream().map(MigrationEntry::getMigrationName).collect(Collectors.toSet());
    final var unappliedMigrations = migrationFiles.stream().filter(file -> !migrationNames.contains(file.getName())).toList();

    //? If we find this, then we can continue...
    if (unappliedMigrations.isEmpty()) {
      console.exec("Nothing to migrate, database is up to date.");
      return Future.succeededFuture();
    }

    //? Apply
    console.info("Applying %d pending migrations...".formatted(unappliedMigrations.size()));

    return RepositoryActor.wrap(() -> {
      sessionFactory.fromStatelessTransaction(session -> {
        for (final var file : unappliedMigrations) {
          final String sql;
          try {
            sql = Files.readString(file.toPath());
          } catch (Exception e) {
            throw new RuntimeException("Failed to read migration file: " + file.getName(), e);
          }

          console.info("Applying migration " + file.getName());

          final var statements = Arrays.stream(sql.split(STATEMENT_BREAKPOINT))
            .map(cmd -> "%s;".formatted(cmd).trim())
            .filter(cmd -> !cmd.equals(";"))
            .toList();

          for (final var command : statements) {
            session.createNativeQuery(command).executeUpdate();
          }

          final var entry = new MigrationEntry();
          final var crc = new CRC32();
          crc.update(sql.getBytes());

          session.insert(
            entry.setMigrationName(file.getName())
              .setChecksum(crc.getValue())
              .setData(DataHelpers.toBase64(sql))
              .setUid(UUID.randomUUID())
          );

          console.exec("Applied " + file.getName());
        }
        return null;
      });
      return null;
    });
  }

  /**
   * The main method to run the migration generation standalone.
   */
  public static Future<Void> migrate(Vertx vertx, SessionFactory sessionFactory) {
    try {
      final var promise = Promise.<Void>promise();
      final var console = ConsoleLogger.getInstance(vertx);
      final var migrationsRepo = new PersistentRepository<>(MigrationEntry.Modules.SYSTEM, MigrationEntry.class, sessionFactory);
      final var classLoader = MigrationHelper.class.getClassLoader();
      final var resource = classLoader.getResource("db/migrations");
      final List<File> migrationFiles = new ArrayList<>();

      // No migration resources packaged yet is a valid state (e.g., first deployment).
      if (resource == null) {
        console.warn("No 'db/migrations' folder found in resources; continuing with zero migration files.");
      } else {
        final var uri = resource.toURI();

        // Scenario A: Running inside a packaged JAR (Docker / Production)
        if ("jar".equals(uri.getScheme())) {
          // Create an isolated virtual filesystem scope to crawl the ZIP contents
          try (FileSystem fileSystem = FileSystems.newFileSystem(uri, Collections.emptyMap())) {
            final var migrationFolder = fileSystem.getPath("db/migrations");
            if (Files.exists(migrationFolder)) {
              try (Stream<Path> walkStream = Files.walk(migrationFolder, 1)) {
                final var tempDir = new File(System.getProperty("java.io.tmpdir"), "extracted-migrations");
                if (!tempDir.exists() && !tempDir.mkdirs()) {
                  throw new IOException("Failed to create temporary migration directory: " + tempDir.getAbsolutePath());
                }

                final var pathsList = walkStream
                  .filter(Files::isRegularFile)
                  .filter(path -> path.getFileName().toString().endsWith(".sql"))
                  .sorted(Comparator.comparing(path -> path.getFileName().toString()))
                  .toList();

                for (final var path : pathsList) {
                  final var fileName = path.getFileName().toString();
                  final var tempFile = new File(tempDir, fileName);

                  // Copy the file out of the JAR into /tmp so executeMigrations can read it as a normal File
                  try (final var is = classLoader.getResourceAsStream("db/migrations/" + fileName)) {
                    if (is != null) {
                      Files.copy(is, tempFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                      migrationFiles.add(tempFile);
                    }
                  }
                }
              }
            } else {
              console.warn("No migration files found in packaged resources; continuing with zero migration files.");
            }
          }
        } else {
          final var outputDir = new File(uri);
          if (!outputDir.exists()) {

            // If we could create this...
            if (outputDir.mkdirs()) {
              ConsoleLogger.getInstance(vertx).exec("Created migration output directory: " + outputDir.getAbsolutePath());
            }

            // Could not do this.
            else {
              promise.fail(new IOException("Failed to create migration output directory: " + outputDir.getAbsolutePath()));
              return promise.future();
            }
          }

          // Get the current sorted files from the local folder
          final var localFiles = outputDir.listFiles();
          if (localFiles != null) {
            migrationFiles.addAll(Arrays.stream(localFiles)
              .sorted(Comparator.comparing(File::getName))
              .toList());
          }
        }
      }

      // Okay then. Proceed with your exact database matching checks
      migrationsRepo.doesTableExist().onFailure(promise::fail).onSuccess(exists -> {
        // If this does not exist, then we can just run the migrations without checking for applied ones, since there are none.
        if (!exists) {
          console.info("Migrations table does not exist, applying all migrations...");
          createMigrationsTable(vertx, sessionFactory)
            .onFailure(promise::fail)
            .onSuccess(v -> executeMigrations(console, sessionFactory, migrationFiles, List.of())
              .onSuccess(ignored -> promise.succeed())
              .onFailure(promise::fail));
          return;
        }

        // Since it exists, we need to check which migrations have been applied and only run the ones that have not been applied.
        migrationsRepo.getMany(
            null,
            new RepositoryOptions<MigrationEntry>(CorrelationContext.from(vertx.getOrCreateContext())).setLimit(3000),
            null
          )
          .onFailure(promise::fail)
          .onSuccess(migrations -> executeMigrations(console, sessionFactory, migrationFiles, migrations)
            .onSuccess(ignored -> promise.succeed())
            .onFailure(promise::fail));
      });

      return promise.future();
    } catch (Exception e) {
      if (e.getCause() != null) {
        return Future.failedFuture(e.getCause());
      }
      return Future.failedFuture(e);
    }
  }

}
