package io.github.the_infinite.framework.data;

import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.reactive.mutiny.Mutiny;
import org.hibernate.tool.schema.TargetType;
import org.hibernate.tool.schema.spi.*;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.util.*;
import java.util.stream.Collectors;
import java.util.zip.CRC32;

import io.github.the_infinite.framework.data.types.RepositoryOptions;
import io.github.the_infinite.framework.env.AppEnvironment;
import io.github.the_infinite.framework.logging.console.ConsoleLogger;
import io.github.the_infinite.framework.logging.correlation.CorrelationContext;
import io.github.the_infinite.framework.utils.DataHelpers;
import io.smallrye.mutiny.Multi;
import io.smallrye.mutiny.Uni;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;

@SuppressWarnings({"unused", "CallToPrintStackTrace", "BlockingMethodInNonBlockingContext"})
public class MigrationHelper {
  private static final String STATEMENT_BREAKPOINT = "--end of statement";

  private static String toJDBCUrl(String url) {
    final var usedUrl = url.trim();
    if (usedUrl.startsWith("jdbc:")) {
      return url;
    }
    return "jdbc:%s".formatted(usedUrl);
  }

  private static URI getMigrationOutputPath(String content) {
    final var name = DataHelpers.createToken(16, 20, 32, "", false);
    final var timestamp = System.currentTimeMillis();
    final var userDir = System.getProperty("user.dir");
    final var resourcesDir = new File(userDir, "src/main/resources/db/migrations");
    final var crc = new CRC32();
    crc.update(content.getBytes());

    return new File(resourcesDir, "%d-%d-%s.sql".formatted(timestamp, crc.getValue(), name)).toURI();
  }

  private static Optional<File> getRuntimeOutputPath() {
    final var classLoader = MigrationHelper.class.getClassLoader();
    try {
      final var resource = classLoader.getResource("db/migrations");
      if (resource == null) {
        return Optional.empty();
      }

      return Optional.of(new File(resource.toURI()));
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  private static Future<Void> createMigrationsTable(Vertx vertx, Mutiny.SessionFactory sessionFactory) {
    final var console = ConsoleLogger.getInstance(vertx);
    final var initialMigrationScriptActions = List.of(
      // Create the policy to ban updates.
      """
        CREATE OR REPLACE FUNCTION __internal_mgt_tm30_ban_updates() RETURNS TRIGGER AS
            $$
            BEGIN
              RAISE EXCEPTION 'Updates to finalized records are not allowed.';
            END;
            $$ LANGUAGE plpgsql;
        """,

      // Create the migration tables.
      """
          create table __database_migrations
          (
            id             BIGINT generated by default as identity,
            createdAt      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP not null,
            uid            UUID                                  not null,
            updatedAt      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP not null,
            checksum       bigint                                not null,
            data           TEXT,
            migration_name varchar(255)                          not null,
            primary key (id)
          );
        """,

      // Create the trigger to prevent updates.
      """
          CREATE TRIGGER prevent_migration_update
              BEFORE
                UPDATE
              ON __database_migrations
              FOR EACH ROW
            EXECUTE FUNCTION __internal_mgt_tm30_ban_updates();
        """,

      // Adding constraints.
      """
        alter table if exists __database_migrations
        drop constraint if exists UKsrnio194w0ic1jdt8h6ihg781;
        """,
      """
        alter table if exists __database_migrations
        add constraint UKsrnio194w0ic1jdt8h6ihg781 unique (uid);
        """,
      """
        alter table if exists __database_migrations
        drop constraint if exists UKllr0ja6npx3lubk3kqyk3t3oe;
        """,
      """
        alter table if exists __database_migrations
        add constraint UKllr0ja6npx3lubk3kqyk3t3oe unique (migration_name);
        """
    );

    try {
      return RepositoryActor.wrap(sessionFactory.withSession(session ->
        Multi.createFrom().iterable(initialMigrationScriptActions).onItem()
          .transformToUniAndConcatenate(command -> session.createNativeQuery(command).executeUpdate())
          .collect().last().chain(v -> session.flush())));
    } catch (Exception e) {
      console.error("Failed to generate initial migration for creating the migrations table: " + e.getMessage());
      return Future.failedFuture(e);
    }
  }

  /**
   * Generates a migration script by comparing the local entity model with the remote database state.
   * Only generates a file if there are actual changes.
   *
   * @return true if changes were detected and a migration script was generated, false otherwise.
   */
  public static boolean generate(Vertx vertx, Mutiny.SessionFactory sessionFactory) {
    final var env = AppEnvironment.getInstance();
    final var console = ConsoleLogger.getInstance(vertx);
    final var annotatedClasses = DataHelpers.findSubclasses(BaseEntity.class);
    annotatedClasses.removeIf(cls -> cls == BaseAuditableEntity.class || cls == BaseEntity.class);
    final var registryBuilder = new StandardServiceRegistryBuilder();
    final var migrationsRepo = new PersistentRepository<>(MigrationEntry.Modules.SYSTEM, MigrationEntry.class, sessionFactory);
    final var repositories = PersistentRepository.instances.keySet();

    //? If we have database classes that are not already registered in the repository instances, we should log a warning about them.
    for (final var entityClass : annotatedClasses) {
      if (repositories.contains(entityClass)) {
        continue;
      }

      console.warn("Database entity class '%s' has no registered repository instance.".formatted(entityClass.getName()));
    }

    if (env.getKind() != AppEnvironment.EnvironmentKind.DEVELOPMENT) {
      console.info("Would not attempt to generate migrations outside of development environment.");
      return false;
    }

    //? Check if this is the root directory of the project.
    if (!new File(System.getProperty("user.dir"), "src/main").exists()) {
      console.warn("Current directory does not appear to be the root of the project, skipping migration generation.");
      return false;
    }

    //? If the migration table does not exist, then we generate a migration just for the
    //? creation of the migration table, since we know that will be needed for any future
    //? migrations to be applied.
    if (!migrationsRepo.doesTableExist().await()) {
      console.info("Migrations table does not exist, generating initial migration for creating the migrations table...");
      createMigrationsTable(vertx, sessionFactory).await();
    }

    final Map<String, Object> dbConfig = Map.of(
      "jakarta.persistence.jdbc.url", toJDBCUrl(env.getPgUrl()),
      "hibernate.dialect", org.hibernate.dialect.PostgreSQLDialect.class.getName()
    );
    registryBuilder.applySettings(dbConfig);

    try (final var serviceRegistry = registryBuilder.build()) {
      final var metadataSources = new MetadataSources(serviceRegistry);
      annotatedClasses.forEach(metadataSources::addAnnotatedClass);
      final Metadata metadata = metadataSources.buildMetadata();
      final var bindings = metadata.getEntityBindings();

      final SchemaManagementTool tool = serviceRegistry.getService(SchemaManagementTool.class);
      if (tool == null) {
        throw new IllegalStateException("SchemaManagementTool service could not be retrieved");
      }
      final SchemaMigrator migrator = tool.getSchemaMigrator(dbConfig);

      final var options = new ExecutionOptions() {
        @Override
        public Map<String, Object> getConfigurationValues() {
          return dbConfig;
        }

        @Override
        public boolean shouldManageNamespaces() {
          return false;
        }

        @Override
        public ExceptionHandler getExceptionHandler() {
          return exception -> {
            throw new RuntimeException("Error executing migration command: " + exception.getMessage(), exception);
          };
        }
      };

      final StringBuilder commands = new StringBuilder();

      //? Now, we can start getting the diff.
      final var targetDescriptor = new TargetDescriptor() {
        @Override
        public EnumSet<TargetType> getTargetTypes() {
          return EnumSet.of(TargetType.SCRIPT);
        }

        @Override
        public ScriptTargetOutput getScriptTargetOutput() {
          return new ScriptTargetOutput() {
            @Override
            public void prepare() {
            }

            @Override
            public void accept(String command) {
              command = command.trim();
              commands.append(command);

              if (!command.endsWith(";")) {
                commands.append(";");
              }

              commands.append("%s%s".formatted(STATEMENT_BREAKPOINT, System.lineSeparator()));
            }

            @Override
            public void release() {
            }
          };
        }
      };

      migrator.doMigration(metadata, options, ContributableMatcher.ALL, targetDescriptor);

      if (commands.isEmpty()) {
        return false;
      }

      final var outputPath = getMigrationOutputPath(commands.toString());
      final var file = new File(outputPath);

      //? If the parent directory does not exist, then we have a problem.
      if (!file.getParentFile().exists()) {
        try {
          if (file.getParentFile().mkdirs()) {
            console.exec("Created directories for migration output: " + file.getParentFile().getAbsolutePath());
          } else {
            throw new IOException("Failed to create directories for migration output: " + file.getParentFile().getAbsolutePath());
          }
        } catch (IOException e) {
          throw new RuntimeException("Could not write migration file: " + outputPath, e);
        }
      }

      //? If we find another migration that applies these same modifications...
      if (Arrays.stream(Objects.requireNonNull(file.getParentFile().list())).anyMatch(migrationFile -> {
        final var parts = migrationFile.split("-", 3);
        final var fileParts = file.getName().split("-", 3);
        final var checksum = parts[1];
        final var currentChecksum = fileParts[1];

        if (parts.length < 3) {
          return false;
        }

        return Objects.equals(parts[1], fileParts[1]);
      })) {
        console.info("A migration file with the same changes already exists, skipping generation.");
        return false;
      }

      //? Doing the most.
      console.info("Found %d entities to generate migrations for.".formatted(bindings.size()));

      //? Now you can say you are doing this because you really are.
      console.info("Generating migration script at " + outputPath.getPath());

      try (final var writer = new FileWriter(file)) {
        //? Append the earlier comments that instruct the user on the specifics of this
        //? file format.
        writer.write("""
          -- This file was generated by comparing the current entity model with the state of the database.
          -- Each command must be separated by the following comment, which is used as a breakpoint
          -- to split the commands when applying the migration: end of statement
          -- If you would like to modify the generated migration, you can edit this file, but be sure
          -- to keep the statement breakpoint comment between each command, otherwise the
          -- migration will fail to apply.
          -- Regards, Tobi of Moovable%s%s
          """.formatted(System.lineSeparator(), commands.toString()));
      } catch (Exception e) {
        throw new RuntimeException("Could not write migration file: " + outputPath, e);
      }

      return true;
    }
  }

  /**
   * Executes the migrations that have been generated and not yet applied to the database.
   * This should be run on application startup to ensure the database is up to date.
   */
  private static void executeMigrations(final ConsoleLogger console, final Mutiny.SessionFactory sessionFactory, final List<File> migrationFiles, final List<MigrationEntry> migrations, final Promise<Void> promise) {
    //? Fetch this first...
    final var migrationNames = migrations.stream().map(MigrationEntry::getMigrationName).collect(Collectors.toSet());
    final var unappliedMigrations = migrationFiles.stream().filter(file -> !migrationNames.contains(file.getName())).toList();

    //? If we find this, then we can continue...
    if (unappliedMigrations.isEmpty()) {
      console.exec("Nothing to migrate, database is up to date.");
      promise.succeed();
      return;
    }

    //? Apply
    console.info("Applying %d pending migrations...".formatted(unappliedMigrations.size()));

    //? Then, we read and apply each one.
    Multi.createFrom().iterable(unappliedMigrations).onItem().transformToUniAndConcatenate(file -> {
      final String sql;
      try {
        sql = Files.readString(file.toPath());
      } catch (Exception e) {
        return Uni.createFrom().failure(e);
      }

      console.info("Applying migration " + file.getName());
      return sessionFactory.withStatelessTransaction((session, tx) ->
        Multi.createFrom()
          .iterable(Arrays.stream(sql.split(STATEMENT_BREAKPOINT))
            .map(cmd -> "%s;".formatted(cmd).trim()).filter(cmd -> !cmd.equals(";")).toList()).onItem()
          .transformToUniAndConcatenate(command -> session.createNativeQuery(command).executeUpdate())
          .collect().last().chain(v -> {
            final var entry = new MigrationEntry();
            final var crc = new CRC32();
            crc.update(sql.getBytes());

            //? Ensure these properties have values; otherwise persisting will fail since
            // they are non-nullable. The rest of the properties are immutable, so we
            // can set them in the return statement.
            // For the immutable properties in a set
            return session.insert(
              entry.setMigrationName(file.getName())
                .setChecksum(crc.getValue())
                .setData(DataHelpers.toBase64(sql))
                .setUid(UUID.randomUUID())
            );
          })).onItem().invoke(() -> console.exec("Applied " + file.getName())).onFailure().invoke(error -> {
        console.error("Failed to apply migration " + file.getName() + ": " + error.getMessage());
        error.printStackTrace();
        promise.fail(error);
      });
    }).collect().last().subscribe().with(promise::succeed, promise::fail);
  }

  /**
   * The main method to run the migration generation standalone.
   */
  public static Future<Void> migrate(Vertx vertx, Mutiny.SessionFactory sessionFactory) {
    try {
      final var promise = Promise.<Void>promise();
      final var console = ConsoleLogger.getInstance(vertx);
      final var migrationsRepo = new PersistentRepository<>(MigrationEntry.Modules.SYSTEM, MigrationEntry.class, sessionFactory);
      final var outputDirBase = getRuntimeOutputPath();

      if (outputDirBase.isEmpty()) {
        promise.fail(new IOException("Failed to determine migration output directory from resources"));
        return promise.future();
      }

      final var outputDir = outputDirBase.get();

      //? Create this is it doesn't exist, otherwise the migration tool will fail when trying to write the output file.
      if (!outputDir.exists()) {
        //? If we could create this...
        if (outputDir.mkdirs()) {
          ConsoleLogger.getInstance(vertx).exec("Created migration output directory: " + outputDir.getAbsolutePath());
        }

        //? Could not do this.
        else {
          promise.fail(new IOException("Failed to create migration output directory: " + outputDir.getAbsolutePath()));
          return promise.future();
        }
      }

      //? Let us get the current sorted files.
      final var migrationFiles = Arrays.stream(Objects.requireNonNull(outputDir.listFiles())).sorted(Comparator.comparing(File::getName)).toList();

      //? Okay then.
      migrationsRepo.doesTableExist().onFailure(promise::fail).onSuccess(exists -> {
        //? If this does not exist, then we can just run the migrations without checking for applied ones, since there are none.
        if (!exists) {
          console.info("Migrations table does not exist, applying all migrations...");
          createMigrationsTable(vertx, sessionFactory).onFailure(promise::fail).onSuccess(v -> executeMigrations(console, sessionFactory, migrationFiles, List.of(), promise));
          return;
        }

        //? Since it exists, we need to check which migrations have been applied and only run the ones that have not been applied.
        migrationsRepo.getMany(
            null,
            new RepositoryOptions<MigrationEntry>(CorrelationContext.from(vertx.getOrCreateContext())).setLimit(3000),
            null
          )
          .onFailure(promise::fail)
          .onSuccess(migrations -> executeMigrations(console, sessionFactory, migrationFiles, migrations, promise));
      });

      return promise.future();
    } catch (Exception e) {
      if (e.getCause() != null) {
        return Future.failedFuture(e.getCause());
      }

      return Future.failedFuture(e);
    }
  }
}
